import { createStore } from "vuex";

export default createStore({
  state: {
    countriesAndCapitals: [
      { country: "Slovenia", city: "Ljubljana", id: 1, abbrev: "SI" },
      { country: "Austria", city: "Vienna", id: 2, abbrev: "AT" },
      { country: "Belgium", city: "Brussels", id: 3, abbrev: "BE" },
      // { country: "Bulgaria", city: "Sofia", id: 4, abbrev: "BG" },
      // { country: "Croatia", city: "Zagreb", id: 5, abbrev: "HR" },
      // { country: "Cyprus", city: "Nicosia", id: 6, abbrev: "CY" },
      // { country: "Czech Republic", city: "Prague", id: 7, abbrev: "CZ" },
      // { country: "Denmark", city: "Copenhagen", id: 8, abbrev: "DK" },
      // { country: "Estonia", city: "Tallinn", id: 9, abbrev: "EE" },
      // { country: "Finland", city: "Helsinki", id: 10, abbrev: "FI" },
      // { country: "France", city: "Paris", id: 11, abbrev: "FR" },
      // { country: "Germany", city: "Berlin", id: 12, abbrev: "DE" },
      // { country: "Greece", city: "Athens", id: 13, abbrev: "GR" },
      // { country: "Hungary", city: "Budapest", id: 14, abbrev: "HU" },
      // { country: "Ireland", city: "Dublin", id: 15, abbrev: "IE" },
      // { country: "Italy", city: "Rome", id: 16, abbrev: "IT" },
      // { country: "Latvia", city: "Riga", id: 17, abbrev: "LV" },
      // { country: "Lithuania", city: "Vilnius", id: 18, abbrev: "LT" },
      // {
      //   country: "Luxembourg",
      //   city: "Luxembourg City",
      //   id: 19,
      //   abbrev: "LU",
      // },
      // { country: "Malta", city: "Valleta", id: 20, abbrev: "MT" },
      // { country: "Netherlands", city: "Amsterdam", id: 21, abbrev: "NL" },
      // { country: "Poland", city: "Warsaw", id: 22, abbrev: "PL" },
      // { country: "Portugal", city: "Lisbon", id: 23, abbrev: "PT" },
      // { country: "Romania", city: "Bucharest", id: 24, abbrev: "RO" },
      // { country: "Slovakia", city: "Bratislava", id: 25, abbrev: "SK" },
      // { country: "Spain", city: "Madrid", id: 26, abbrev: "ES" },
      // { country: "Malta", city: "Valleta", id: 27, abbrev: "MT" },
      // { country: "Sweden", city: "Stockholm", id: 28, abbrev: "SE" },
    ],
  },
  mutations: {},
  actions: {},
  modules: {},
});
